# -*- coding: utf-8 -*-
{
    "name": "MotoGene Promotion Engine",
    "version": "18.0.1.12.3",
    "category": "Sales/Sales",
    "summary": "Configurable conditional promotion engine for MotoGene sales orders.",
    "author": "WanBadreen",
    "license": "LGPL-3",
    "depends": ["sale_management", "sale_stock", "product"],
    "data": [
        "security/ir.model.access.csv",
        "security/scratch_redemption_rules.xml",
        "views/promotion_program_views.xml",
        "views/scratch_setup_transfer_views.xml",
        "views/promotion_exclusion_views.xml",
        "views/scratch_shortage_wizard_views.xml",
        "views/scratch_redemption_views.xml",
        "views/scratch_redemption_wizard_views.xml",
        "views/sale_order_views.xml",
        "views/stock_picking_views.xml",
        "report/scratch_picking_report.xml",
    ],
    "demo": [],
    "installable": True,
    "application": True,
}
